Repository MicrosoftDocs/azure-devops-yaml-schema, pull requests merged in 2023-01, with the labels that each got.

#76 Change PR branch message
  content/pr.md
Labels: Change sent to author, ready-to-merge, docs-editor-pilot, azure-devops-pipelines/svc

#85 Binary code coverage for Linux
  task-reference/dotnet-core-cli-v2.md
Labels: Change sent to author, ready-to-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc, qualifies-for-auto-merge

#83 Change UsePythonVersion documentation to use the new syntax
  task-reference/use-python-version-v0.md
Labels: Change sent to author, do-not-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc, qualifies-for-auto-merge

#79 Fixing extra break
  task-reference/includes/deploy-winrm-setup.md
Labels: Change sent to author, do-not-merge, devops/prod, devops-cicd-tasks/tech, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc

#74 Update docker-compose-v0.md
  task-reference/docker-compose-v0.md
Labels: Change sent to author, ready-to-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc

#73 Add link to file matching patterns page for SearchPattern attribute
  task-reference/publish-symbols-v2.md
Labels: Change sent to author, ready-to-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc
