Repository MicrosoftDocs/azure-devops-yaml-schema, pull requests merged in 2023-05, with the labels that each got.

#149 Update azure-powershell-v2.md
  task-reference/azure-powershell-v2.md
Labels: Change sent to author, do-not-merge, ready-to-merge, azure-devops-pipelines/svc, qualifies-for-auto-merge

#144 Added CmdLine input script use case
  task-reference/cmd-line-v2.md
Labels: Change sent to author, do-not-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc, qualifies-for-auto-merge

#140 Update rm-app-service-troubleshoot-shared.md
  task-reference/includes/rm-app-service-troubleshoot-shared.md
Labels: Change sent to author, do-not-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc, qualifies-for-auto-merge

#163 Update azure-function-app-v2.md
  task-reference/azure-function-app-v2.md
Labels: Change sent to author, do-not-merge, docs-editor-pilot, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc, qualifies-for-auto-merge

#161 Updating the dotnet core sdk version dependency of the PCCRV2 task [DONT MERGE]
  task-reference/media/dotnet7.PNG
  task-reference/publish-code-coverage-results-v2.md
Labels: Change sent to author, do-not-merge, azure-devops-pipelines/svc, azure-devops-pipelines-tasks/subsvc, needs-human-review
